apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: order_management
    user: ${GF_DATABASE_USER}
    secureJsonData:
      password: ${GF_DATABASE_PASSWORD}
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
  
  - name: Traefik
    type: prometheus
    access: proxy
    url: http://traefik:8080
    editable: true